name: CI Básico

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Mostrar mensaje CI
        run: echo "✅ CI ejecutado correctamente desde GitHub Actions"
